[General]
background_image=img/background.png
avatar=img/avatar.png
usernameIcon=img/username.png
passwordIcon=img/lock.png
sleepIcon=img/moon.png
restartIcon=img/arrow-clockwise.png
shutdownIcon=img/power.png
sessionIcon=img/desktop.png

fancyDateFont=fonts/RoshidaValentines.ttf
sessionSwitcherEnabled=false

backgroundColor="#2a2d3d"
cardBackgroundColor="#313445"
borderColor="#494d64"
primaryTextColor="white"
placeholderTextColor="#7d8296"
secondaryTextColor="#232634"

red="#ed8796"
orange="#f5a97f"
yellow="#eed49f"
green="#a6da95"
blue="#91d7e3"
purple="#c6a0f6"


waveBlockWidth=15
waveBlockSpacing=4
waveBaseHeight=60

waveAmplitude=160
waveFrequency=6
waveSpeed=0.008

waveAmplitude2=160
waveFrequency2=7
waveSpeed2=0.016